name: Compile

on:
  label:
    types:
      - created
      - edited
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with AHK v2
        uses: nukdokplex/autohotkey-build@v1
        with:
          version: v2.0.2
          x64: true
          x64_suffix: ""
          compression: upx
          in: ""
          out: build
      - name: Do Something with builded scripts
        shell: pwsh
        run: |
          ls build
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/Protoman.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
